[[LAZperf]]
arch = "aarch64"
git-tree-sha1 = "0ae46b91cdb61579e28bab1ebb902849689a1591"
os = "macos"

    [[LAZperf.download]]
    sha256 = "408132869f39ee7355af965b22d1f474441ce950d9b0f1f26ed4c025aa392938"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.aarch64-apple-darwin.tar.gz"
[[LAZperf]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "399e352450541deca20c26dc4187006e8b95f2d5"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "9d4416c087cf5c9dd26c498f165a92a25d6d3ae6cae6cc874c95e669a0adf27b"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LAZperf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a661c9cea13b32a6a71cdf4ee83e22f4064b1aff"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "54b2478dd36193a70d9d92587fdab8390af8da77ba66c8d1772272a6a8a5c7ca"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LAZperf]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bac0349c8bdf780b55afe044a36e35f6c8322bf"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "f9f7c6772005a1d2d8e099ce03f03b9b7179fb184b78df460a4c5bd2c9d6bdd5"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[LAZperf]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe0282763039f9ef20b84fbd82d9072a203965fe"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "f7f5f6a0890b242883d3a25cfa97c1d083d53a6fd42d26ec34a1b9e81c2089a2"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[LAZperf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1182d30270a70f755f6c5f758d54136283a6bc88"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "0821bccc293ec0196549a4ecba5c63cd14200730102ab91f03fd8c1dc6ae7688"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LAZperf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b59a2220be8ad6c11a395dfa122ee55dde03bc16"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "7e1d8a84a8b275c143e5cc85290410d18551da9bda93fbbe2f0a658c11d9faec"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LAZperf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4582c73971cf6e74eeb20e5225b95cc9644778a"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "867dff33347777459567075929e26a4a2c577d40939e4f925950276832a23b33"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LAZperf]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "853e6fbd4fabf0de824c54e07abe7abdf5ae7877"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "c4009d2a8bf9cc76a0a9f8440f06865ec52b596ce8328802146899ae2290c34a"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LAZperf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fe796a1bd08c3bd6b4a50e1dd4ec4ffb533d6c1"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "052e507a9ad9c32f0eb9d7fd968490bdb0379e48ba776c5ba8c7d67b6a8e3f1d"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LAZperf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "011fddf40bd68384c5d344eda94f1fdc5504ab26"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "956f7d46d201c987914396727d210253f244a79f50d76a2d6605838a1cd63cc5"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LAZperf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ea03abeaa2a4291abb0d66497e265c15f8dec3e"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "d0247968a59d055738e4fd2157a55ea4653c9c2ac9d5edf8bf4710e08ea92b12"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LAZperf]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f05a36bebb3b9f675354f4633bbd380f9ca48d57"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "1029571424e625dc8670b59b46b1d5ee0c741b516070d3d065d5f8fc59b360e0"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LAZperf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6d92f7640bb2f5eb909924e16eb8833bc62ea86"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "dcf529bcbbef81871af31e56c9c0aa6982f1df2adb8bc401ee2d71e3d5ff57dc"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.i686-linux-gnu-cxx03.tar.gz"
[[LAZperf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7986cfbe4bb1af0b28e1fa8718c67912004f65e"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "aa17ed0a7039e1547d9d50246e738f0880c43b0eaa796e8bf3bbaadd057209c7"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.i686-linux-gnu-cxx11.tar.gz"
[[LAZperf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3ff27b04ef981b8663807d38fc8dab778011e99"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "b8f7129d3a1eb8d574ff7da60f55f88cb2d5eac9f2a76cf72b3c7136635e22ff"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.i686-linux-musl-cxx03.tar.gz"
[[LAZperf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22c9cb984c7797c3ec037ba532be06c503c4727d"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "adebd8496ab10f3e16b9b6981589af09900f2c40be1cb05b9837c37a2752482f"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.i686-linux-musl-cxx11.tar.gz"
[[LAZperf]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ecda774bd5b815b8c29da665e27d470a5c78b8a"
os = "windows"

    [[LAZperf.download]]
    sha256 = "5d7eb4a5243155e2e11cdee24074fbe5706003d5b794b4c2f4c9918a625e10b6"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[LAZperf]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b6e2d7f44f55bda6745d9f699ca9465d502f2be"
os = "windows"

    [[LAZperf.download]]
    sha256 = "b0267e7c11735e9d3069d3fde24019bb8ddb39dcb8fb24c5d5cbe272f7d9985a"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[LAZperf]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13811df14f63aeb94ebd1b7d381e5ef605bafcb1"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "2da0413a3fefd4e6ca4a8af92ec34622c1ede38035e20d12b78d90974e8204c6"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LAZperf]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c9126c174933dc0cddc96e36f5f2b7658cde8e2"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "caa6efd134fdddaea39b93b9f8898203cd97f513f6c4e3db6473745f36241694"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LAZperf]]
arch = "x86_64"
git-tree-sha1 = "bbfe10209b749bb828b8a6e8ae4791ada84bea4c"
os = "macos"

    [[LAZperf.download]]
    sha256 = "b86d3482ae1fed8d676949e9b140374e845e86741875a63895656d05127084b1"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-apple-darwin.tar.gz"
[[LAZperf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9db37bbf4201a17eb46f1cc8c6ebab464f5a25c"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "b616a7f57ab689f0483fa9acb951117b821817c34ac5ffc77647a849ac68d18e"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LAZperf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcd01556a199c76281cad5984c377de2930c1fbd"
libc = "glibc"
os = "linux"

    [[LAZperf.download]]
    sha256 = "66ee23f777bb0031f830d286621babcb04a5f8c19386f180d95f1a8fd5ab1acb"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LAZperf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5964b19a4d419a0a545401a94501180c16878fe3"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "00f329509a22e4cefdcb61be0c6f1dce5de0890af2a76117a5d696567ab00803"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[LAZperf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b571284c2d0b248e2b7b9e49abf01c085496a217"
libc = "musl"
os = "linux"

    [[LAZperf.download]]
    sha256 = "4185b3a065b390088aa033336351eaa71e81aa8780cc942a1fe7b4896838e455"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[LAZperf]]
arch = "x86_64"
git-tree-sha1 = "0558acb9fa82da37c9e3a6728d441abf6a520e64"
os = "freebsd"

    [[LAZperf.download]]
    sha256 = "79b5d5b5882c3ef3d9aacea5a761f95e2d019cff2195cfe19eebb307fcc57542"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-unknown-freebsd.tar.gz"
[[LAZperf]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0eb93aaf6a3df2c865491e7d4e4860911c1736ae"
os = "windows"

    [[LAZperf.download]]
    sha256 = "2dd82e88a930cce58dce93d92a4566681480773d1de1fc7e8686a86c00a7cbb1"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LAZperf]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a3a86f9d3629724674d3d3333a30b03d361d95c"
os = "windows"

    [[LAZperf.download]]
    sha256 = "450e98c0266ecc5f5723ba8e49850dce63a90b41a996b0774b5f80f4f1b5dff0"
    url = "https://github.com/JuliaBinaryWrappers/LAZperf_jll.jl/releases/download/LAZperf-v3.3.0+0/LAZperf.v3.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
