# Autogenerated wrapper script for LAZperf_jll for aarch64-apple-darwin
export liblazperf

JLLWrappers.@generate_wrapper_header("LAZperf")
JLLWrappers.@declare_library_product(liblazperf, "@rpath/liblazperf.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblazperf,
        "lib/liblazperf.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
